import '../common.dart';
import 'day01.dart';
import 'day02.dart';
import 'day03.dart';
import 'day04.dart';
import 'day05.dart';
import 'day06.dart';
import 'day07.dart';
import 'day08.dart';
import 'day09.dart';
import 'day10.dart';
import 'day11.dart';
import 'day12.dart';
import 'day13.dart';
//import 'day14.dart';
//import 'day15.dart';
//import 'day16.dart';
//import 'day17.dart';
//import 'day18.dart';
//import 'day19.dart';
//import 'day20.dart';
//import 'day21.dart';
//import 'day22.dart';
//import 'day23.dart';
//import 'day24.dart';

void main() async {
  var aoc = AOC();
  addDay01(aoc: aoc);
  addDay02(aoc: aoc);
  addDay03(aoc: aoc);
  addDay04(aoc: aoc);
  addDay05(aoc: aoc);
  addDay06(aoc: aoc);
  addDay07(aoc: aoc);
  addDay08(aoc: aoc);
  addDay09(aoc: aoc);
  addDay10(aoc: aoc);
  addDay11(aoc: aoc);
  addDay12(aoc: aoc);
  addDay13(aoc: aoc);
  //addDay14(aoc: aoc);
  //addDay15(aoc: aoc);
  //addDay16(aoc: aoc);
  //addDay17(aoc: aoc);
  //addDay18(aoc: aoc);
  //addDay19(aoc: aoc);
  //addDay20(aoc: aoc);
  //addDay21(aoc: aoc);
  //addDay22(aoc: aoc);
  //addDay23(aoc: aoc);
  //addDay24(aoc: aoc);
  (await aoc.solveAll(solveExamples: false)).printStats();
}
